---
development:
  API_URL: "http://localhost:3000/api/v1"
  APP_URL: "http://localhost:9292"
  REGLINK_EXPIRATION: "30"
test:
  API_URL: "http://localhost:3000/api/v1"
  APP_URL: "http://localhost:9292"
  REGLINK_EXPIRATION: "30"

production:
