---
development:
  API_URL: http://localhost:3000/api/v1
  APP_URL: http://localhost:9292

test:
  API_URL: http://localhost:3000/api/v1
  APP_URL: http://localhost:9292

production:
  API_URL: http://vitae2-api.herokuapp.com/api/v1
  APP_URL: http://vitae2.herokuapp.com
