# Rename file to secrets.yml to get started for development or test
---
development:

  MSG_KEY: <`rake generate:msg_key`>
  REDIS_URL: <provision Redis instance and provide URL>

  GOOGLE_OAUTH2_CLIENT_ID: <Google OAUTH2>
  GOOGLE_OAUTH2_CLIENT_SECRET: <Google OAUTH2>

  SIGNING_KEY: <rake integrity:url>
  VERIFY_KEY: <rake integrity:url>

test:

development:
