---
# Rename file to secrets.yml to get started for development or test

development:
  SESSION_SECRET: IAFvVKG7umawEHSmBP++INBXWsDK+BDEHpvvnLUyH69VOQvFP63plArksvuNhfq9ouyOJraVFDXxbz0to3Pzqg==
  MSG_KEY: ok7jAfDr1AVOFhYwJfEfURcBKKE+tARZEx7nHrui0ks=
test:
  SESSION_SECRET: jsvDwSwCGf8bBtBa6eA5ANax8ta4mdJeZOh1KVoa7gDExvtdHYIgQv2AY5x9dBmoSJq4xXsIu5YV1Zngsgs9lg==
  MSG_KEY: eb05smRVz1cER0X4UiXu/h35qshADQ765cm776oPmvY=